services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html-server
    ports:
      - "8000:8000"

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    depends_on:
      - app
